"""Write brand.ts with colors, fonts, AND spacing tokens extracted from the original site."""
from pathlib import Path
from stages.stage1_scraper.models import ScrapedData


def write_brand_tokens(project_dir: Path, data: ScrapedData) -> None:
    colors = data.colors.palette
    fonts = data.typography.families
    spacing = data.spacing_tokens

    primary = colors[0].hex if colors else "#1a1a2e"
    secondary = colors[1].hex if len(colors) > 1 else "#16213e"
    accent = colors[2].hex if len(colors) > 2 else "#0f3460"
    bg = next((c.hex for c in colors if "background" in c.usage), "#ffffff")
    text_color = next((c.hex for c in colors if "text" in c.usage), "#333333")

    font_primary = fonts[0].strip("'\"") if fonts else "Inter"
    font_secondary = fonts[1].strip("'\"") if len(fonts) > 1 else font_primary

    # Build spacing scale from extracted tokens
    all_spacing = list(dict.fromkeys(
        spacing.common_paddings[:4] + spacing.common_margins[:4] + spacing.common_gaps[:2]
    ))
    spacing_scale = all_spacing[:8] if all_spacing else ["4px", "8px", "16px", "24px", "32px", "48px"]

    radii = spacing.common_radii[:3] or ["0px"]
    shadow = spacing.common_shadows[0] if spacing.common_shadows else "none"

    brand_ts = f"""// Auto-generated by akquipe (stage3_imitate) — brand tokens for {data.domain}
export const BRAND_COLORS = {{
  primary: "{primary}",
  secondary: "{secondary}",
  accent: "{accent}",
  background: "{bg}",
  text: "{text_color}",
  palette: {[c.hex for c in colors[:8]]},
}} as const;

export const BRAND_FONTS = {{
  primary: "'{font_primary}', sans-serif",
  secondary: "'{font_secondary}', sans-serif",
  bodySize: "{data.typography.body_size or "16px"}",
  lineHeight: "{data.typography.line_height or "1.6"}",
}} as const;

export const BRAND_SPACING = {{
  scale: {spacing_scale},
  radii: {radii},
  shadow: "{shadow}",
}} as const;

export const BRAND = {{
  colors: BRAND_COLORS,
  fonts: BRAND_FONTS,
  spacing: BRAND_SPACING,
  domain: "{data.domain}",
  originalUrl: "{data.url}",
}} as const;

// convenience aliases
export const brand = BRAND;
export const BRAND_COLOR = BRAND_COLORS;
export const BRAND_FONT = BRAND_FONTS;
"""

    lib_dir = project_dir / "src" / "lib"
    lib_dir.mkdir(parents=True, exist_ok=True)
    (lib_dir / "brand.ts").write_text(brand_ts, encoding="utf-8")

    # CSS variables in globals.css
    css_vars = "\n".join([
        f"    --color-primary: {primary};",
        f"    --color-secondary: {secondary};",
        f"    --color-accent: {accent};",
        f"    --color-bg: {bg};",
        f"    --color-text: {text_color};",
        f"    --font-primary: '{font_primary}', sans-serif;",
        f"    --font-secondary: '{font_secondary}', sans-serif;",
    ])

    globals_css_path = project_dir / "src" / "app" / "globals.css"
    if globals_css_path.exists():
        existing = globals_css_path.read_text(encoding="utf-8")
        brand_vars = f"\n/* akquipe brand tokens */\n:root {{\n{css_vars}\n}}\n"
        globals_css_path.write_text(existing + brand_vars, encoding="utf-8")
