from pathlib import Path
from stages.stage1_scraper.models import ScrapedData


def write_brand_tokens(project_dir: Path, data: ScrapedData) -> None:
    colors = data.colors.palette
    fonts = data.typography.families

    primary = colors[0].hex if colors else "#1a1a2e"
    secondary = colors[1].hex if len(colors) > 1 else "#16213e"
    accent = colors[2].hex if len(colors) > 2 else "#0f3460"
    bg = next((c.hex for c in colors if "background" in c.usage), "#ffffff")
    text_color = next((c.hex for c in colors if "text" in c.usage), "#333333")

    font_primary = fonts[0].strip("'\"") if fonts else "Inter"
    font_secondary = fonts[1].strip("'\"") if len(fonts) > 1 else font_primary

    brand_ts = f"""// Auto-generated by akquipe — scraped brand tokens for {data.domain}
export const brand = {{
  colors: {{
    primary: "{primary}",
    secondary: "{secondary}",
    accent: "{accent}",
    background: "{bg}",
    text: "{text_color}",
    palette: {[c.hex for c in colors[:8]]},
  }},
  fonts: {{
    primary: "{font_primary}",
    secondary: "{font_secondary}",
    bodySize: "{data.typography.body_size or "16px"}",
    lineHeight: "{data.typography.line_height or "1.6"}",
  }},
  domain: "{data.domain}",
  originalUrl: "{data.url}",
}} as const;

export type Brand = typeof brand;
"""

    lib_dir = project_dir / "src" / "lib"
    lib_dir.mkdir(parents=True, exist_ok=True)
    (lib_dir / "brand.ts").write_text(brand_ts, encoding="utf-8")

    # Tailwind config with brand CSS variables
    css_vars = "\n".join([
        f"    --color-primary: {primary};",
        f"    --color-secondary: {secondary};",
        f"    --color-accent: {accent};",
        f"    --color-bg: {bg};",
        f"    --color-text: {text_color};",
        f"    --font-primary: '{font_primary}', sans-serif;",
        f"    --font-secondary: '{font_secondary}', sans-serif;",
    ])

    globals_css_path = project_dir / "src" / "app" / "globals.css"
    if globals_css_path.exists():
        existing = globals_css_path.read_text(encoding="utf-8")
        brand_vars = f"\n/* akquipe brand tokens */\n:root {{\n{css_vars}\n}}\n"
        globals_css_path.write_text(existing + brand_vars, encoding="utf-8")
